PROOT:=/home/petalinux/emblnx/labs/lab3/ZYBO_petalinux_v2015_4
INSTANCE:=linux/rootfs/myapp
-include /home/petalinux/emblnx/labs/lab3/ZYBO_petalinux_v2015_4/build/linux/Makefile.export
-include /home/petalinux/emblnx/labs/lab3/ZYBO_petalinux_v2015_4/build/linux/rootfs/Makefile.export
-include /home/petalinux/emblnx/labs/lab3/ZYBO_petalinux_v2015_4/build/linux/rootfs/apps/myapp/Makefile.export
CONFIGFILE:=/home/petalinux/emblnx/labs/lab3/ZYBO_petalinux_v2015_4/subsystems/linux/configs/rootfs/config
dir_apps_y=/home/petalinux/emblnx/labs/lab3/ZYBO_petalinux_v2015_4/components/apps/myapp

